#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += zaw806_nt35521s_hd720_dsi_vdo_txdqc_TXDT500SYPA.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
